# Generated by Django 3.1.3 on 2020-11-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Payable'), ('R', 'Recievable'), ('C', 'Clear')], default='C', max_length=1)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.acc')),
            ],
        ),
    ]
