# Generated by Django 3.1.3 on 2020-11-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amt', models.IntegerField()),
                ('credit_amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.acc')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp.acc')),
            ],
        ),
    ]
