# Generated by Django 3.1.3 on 2020-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_credit_debit_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='credit_amt',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='debit_amt',
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debit',
            name='debit_amt',
            field=models.IntegerField(default=0),
        ),
    ]
