# Generated by Django 3.1.3 on 2020-11-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_auto_20201115_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
